### ISSUE TITLE
Routes are not working properly

### ISSUE THREAD

**Issue by pavanSaberjack** [mapbox/MapboxDirections.swift#105]
I was testing direction API, tried to get direction for two coordinates (45.52258, -122.6732)  & (45.62258, -122.6732)
The polyline which is getting drawn is totally wrong. It is not using road path.
Please someone help me if there are any mistakes. Otherwise I have to try other libraries  

    - (void)addTestRoute
    {
    NSArray<JobLocation *> *array = [LocationsManager getJobLocations];
    NSArray<MBWaypoint *> *waypoints = @[[[MBWaypoint alloc] initWithCoordinate:CLLocationCoordinate2DMake(45.52258, -122.6732) coordinateAccuracy:-1 name:@"Mapbox"], [[MBWaypoint alloc] initWithCoordinate:CLLocationCoordinate2DMake(45.62258, -122.6732) coordinateAccuracy:-1 name:@"Mapbox"]];

    MBRouteOptions *options = [[MBRouteOptions alloc] initWithWaypoints:waypoints
                                                      profileIdentifier:@"mapbox/driving"];
    options.includesSteps = YES;
    
    MBDirections *directions = [MBDirections sharedDirections];
    
    NSURLSessionDataTask *task = [directions calculateDirectionsWithOptions:options completionHandler:^(NSArray<MBWaypoint *> * _Nullable waypoints, NSArray<MBRoute *> * _Nullable routes, NSError * _Nullable error) {
        if (error) {
            NSLog(@"Error calculating directions: %@", error);
            return;
        }
        
        MBRoute *route = routes.firstObject;
        MBRouteLeg *leg = route.legs.firstObject;
        if (leg) {
            NSLog(@"Route via %@:", leg);
            
            NSLengthFormatter *distanceFormatter = [[NSLengthFormatter alloc] init];
            NSString *formattedDistance = [distanceFormatter stringFromMeters:leg.distance];
            
            NSDateComponentsFormatter *travelTimeFormatter = [[NSDateComponentsFormatter alloc] init];
            travelTimeFormatter.unitsStyle = NSDateComponentsFormatterUnitsStyleShort;
            NSString *formattedTravelTime = [travelTimeFormatter stringFromTimeInterval:route.expectedTravelTime];
            
            NSLog(@"Distance: %@; ETA: %@", formattedDistance, formattedTravelTime);
            
            for (MBRouteStep *step in leg.steps) {
                NSLog(@"%@", step.instructions);
                NSString *formattedDistance = [distanceFormatter stringFromMeters:step.distance];
                NSLog(@"— %@ —", formattedDistance);
            }
        }
        
        if (route.coordinateCount) {
            // Convert the route’s coordinates into a polyline.
            CLLocationCoordinate2D *routeCoordinates = malloc(route.coordinateCount * sizeof(CLLocationCoordinate2D));
            [route getCoordinates:routeCoordinates];
            MGLPolyline *routeLine = [MGLPolyline polylineWithCoordinates:routeCoordinates count:route.coordinateCount];
            
            // Add the polyline to the map and fit the viewport to the polyline.
            [self.mapView addAnnotation:routeLine];
            [self.mapView setVisibleCoordinates:routeCoordinates count:route.coordinateCount edgePadding:UIEdgeInsetsZero animated:YES];
            
            // Make sure to free this array to avoid leaking memory.
            free(routeCoordinates);
        }
    }];
    }

**Comment by aleberguer** [comment]
I am facing the same issue, the polyline is drawn across the blocks. Any solutions for this?

![img_0253](https://cloud.githubusercontent.com/assets/5271876/23269867/b4ed9664-f9d0-11e6-8400-43323c75521b.PNG)

**Comment by aleberguer** [comment]
I changed the Directions API version to V4, by using RouteOptionsV4 and now it's working.
For a route of 200 km in the city, V5 is bringing 74 coordinate points, which is absurd. With V4 for the same route, the API is bringing 2781 coordinates points and is correct.

**Comment by frederoni** [comment]
I'm not sure what the default shape resolution is but try setting it to full:
```
options.routeShapeResolution = MBRouteShapeResolutionFull;
```

**Comment by 1ec5** [comment]
Indeed, you’ll want to specify a full `routeShapeResolution`. By default, you get a simplified route line suitable for use in an overview (zoomed out to show the whole route at once on screen). This is consistent with the [Directions API](https://www.mapbox.com/api-documentation/#retrieve-directions), which defaults `overview` to `simplified`.

**Comment by aleberguer** [comment]
Thank you both, setting routeShapeResolution resolved my issue.
