### ISSUE TITLE
Error with CocoaPods integration

### ISSUE THREAD

**Issue by anatoliykant** [mapbox/MapboxDirections.swift#112]
instead of pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', '~> 0.8'

 must be pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :tag => 'v0.8.0'

**Comment by 1ec5** [comment]
Thanks, that was a typo. In fact, you can now simply write:

```podfile
pod 'MapboxDirections.swift', '~> 0.8'
```

because we’ve pushed the podspec to CocoaPods.org.
