### ISSUE TITLE
Adopt JSONDecoder

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#134]
Swift 4 introduces JSONDecoder and built-in coding protocols, which should allow us to remove the majority of code from this library.

/cc @bsudekum @frederoni

**Comment by 1ec5** [comment]
#221 stalled because JSONDecoder [performs poorly compared to NSCoding](https://bugs.swift.org/browse/SR-6252), at least for the structures we’re trying to serialize and deserialize. The Swift 5 release notes don’t mention anything specifically related to JSONDecoder, but we should check it out nonetheless. Perhaps we should also look into adopting Codable without adopting JSONDecoder.

**Comment by frederoni** [comment]
Might be worth investigating https://github.com/apple/swift-protobuf
Swift-protobuf does support serializing and deserializing a fixed JSON format which will most likely not align with the api directions response. However, it could turn out to be more convenient to generate the models and manually a write schema adapter, compared to manual NSCoding or half-manual Coding code.

**Comment by juliengdt** [comment]
Up ! Any news/updates ?

**Comment by frederoni** [comment]
@juliengdt Support for Codable is being worked on in #382
