### ISSUE TITLE
Requests should indicate whether Core Navigation is present

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#136]
[Core Navigation](https://github.com/mapbox/mapbox-navigation-ios/) drives a specific usage pattern of the Directions API (for turn-by-turn guidance). To help us track usage of Core Navigation and the navigation SDK overall, the [user agent string](https://github.com/mapbox/MapboxDirections.swift/blob/d7fa84b2b7642fa849425177a195e18bf6534ff2/MapboxDirections/MBDirections.swift#L10-L52) should indicate whether that library is installed.

Specifically, if `NSClassFromString("MBRouteController")` returns a value, the user agent string should include an additional component like `CoreNavigation/0.4.0`. Normally, getting Core Navigation’s version would be a good use case for using the [`MapboxCoreNavigationVersionString`](https://github.com/mapbox/mapbox-navigation-ios/blob/3b9cd495abf82063dc348b4d3ba4923e95f4e919/MapboxCoreNavigation/MapboxCoreNavigation.h#L7) global constant provided by Xcode. However, we don’t want a cyclical dependency on Core Navigation in this library. So instead we’d get the version string from the bundle containing `MBRouteController`.

/cc @bsudekum @ericrwolfe

**Comment by 1ec5** [comment]
In addition to checking for the existence of a particular class, which can sometimes yield false positives, we could check if a bundle exists with the [expected bundle ID](https://github.com/mapbox/mapbox-navigation-ios/blob/3b9cd495abf82063dc348b4d3ba4923e95f4e919/MapboxNavigation.xcodeproj/project.pbxproj#L1670). However, CocoaPods generates its own bundle identifier for the overall Pods framework and doesn’t maintain a separate bundle for Core Navigation.

**Comment by 1ec5** [comment]
We’ll also want to add a query parameter to each request indicating the presence of Core Navigation to ensure robustness.

/cc @mick

**Comment by danpat** [comment]
Just a quick note - the `User-Agent` header doesn't make it through to our backend services.  [CloudFront replaces the `User-Agent` header](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-headers-behavior) with the value `Amazon CloudFront` before forwarding.

If we use a header, it'll need to be a custom one.

**Comment by 1ec5** [comment]
mapbox/mapbox-navigation-ios#2221 indicates the presence of the MapboxNavigation module in navigation telemetry events (which are predicated on the presence of MapboxCoreNavigation). This library doesn’t send telemetry, but it could use a similar mechanism to indicate the presence of MapboxCoreNavigation.
