### ISSUE TITLE
Map Matching API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#158]
Given the [Mapbox Map Matching API](https://www.mapbox.com/api-documentation/#retrieve-a-match)’s similarity to the Directions API, we could pretty cleanly implement support for the former in this library. Here’s one possible design:

* The Directions class would gain a new `match(_:completionHandler:)` method that takes a MatchOptions object based on [these options](https://www.mapbox.com/api-documentation/#retrieve-a-match).
* The completion handler would accept an array of [Match](https://www.mapbox.com/api-documentation/#match-object) objects, an array of [Tracepoint](https://www.mapbox.com/api-documentation/#tracepoint-object) objects, and an optional Error.
* Match would be a subclass of Route.
* Tracepoint would be a subclass of Waypoint.

/cc @bsudekum

**Comment by ericrwolfe** [comment]
This will be unblocked by https://github.com/Project-OSRM/osrm-backend/issues/4669.

**Comment by 1ec5** [comment]
It sounds like Project-OSRM/osrm-backend#4669 blocks a particular use case for this feature, but there’s nothing stopping us from implementing Map Matching API support for general use cases, as Mapbox Java Services has.

**Comment by ericrwolfe** [comment]
> but there’s nothing stopping us from implementing Map Matching API support for general use cases, as Mapbox Java Services has.

Indeed. We can go ahead and implement this whenever we have the bandwidth, but once https://github.com/Project-OSRM/osrm-backend/issues/4669 lands it'll make testing this use case a lot easier.

**Comment by ericrwolfe** [comment]
A new `waypoints` parameter (https://github.com/Project-OSRM/osrm-backend/pull/4732) was added to the map matching API which makes this usable for turn-by-turn navigation.

https://github.com/mapbox/mapbox-navigation-android/issues/659 describes similar changes that need to be added to support map matching and custom routes in Mapbox Java and Mapbox Navigation on Android.
