### ISSUE TITLE
Cannot convert value of type 'IndexSet.Type' to expected argument type '[AnyClass]?'

### ISSUE THREAD

**Issue by 1cookspe** [mapbox/MapboxDirections.swift#161]
This error is in "MBIntersection.swift", located at "https://github.com/mapbox/MapboxDirections.swift/blob/master/MapboxDirections/MBIntersection.swift", under the "MapBoxDirections" folder. 

I receive the error of "Cannot convert value of type 'IndexSet.Type' to expected argument type '[AnyClass]'". 

![screen shot 2017-08-08 at 4 08 19 pm](https://user-images.githubusercontent.com/8737691/29092226-9d1d9ab0-7c53-11e7-8b50-3f599993f384.png)

Any ideas on why this happens? Or how to fix it! Thanks for any help!

**Comment by frederoni** [comment]
Thank you for your report.
What version of Xcode are you using?
Did you integrate MapboxDirections.swift using CocoaPods or Carthage?

**Comment by 1cookspe** [comment]
Thanks for your response! 

I am using Xcode 8.3.3.

I added MapboxDirections.swift via CocoaPods

**Comment by frederoni** [comment]
What does your Podfile look like? Is your application written in Swift or Objective-C?

**Comment by 1cookspe** [comment]
The Podfile line I used to import MapboxDirections is:

`pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'`

The application is written in Swift.

**Comment by frederoni** [comment]
Oh, the latest version is also using Swift 3. Try:
```ruby
pod 'MapboxDirections.swift', '~> 0.10.1'
```

**Comment by 1cookspe** [comment]
Thanks, it works now! I just needed to update it! Thanks so much for your help!
