### ISSUE TITLE
can't reach mauverType, maneuverDirection not visible from Objective-C

### ISSUE THREAD

**Issue by greenzeal** [mapbox/MapboxDirections.swift#163]
Dear friends, 
Using your maps and want to reach mauverType, maneuverDirection properties of the MBRouteStep but can't. Please can you suggest the best way to solve this problem?

Thanks!

**Comment by 1ec5** [comment]
Duplicate of #117.

**Comment by greenzeal** [comment]
dupilicate but no answer :(

**Comment by 1ec5** [comment]
Unfortunately, there’s no workaround of this issue other than writing some Swift code to interact with those properties. #117 contains some ideas about fixing the issue. Unfortunately this is a good example of the downside of implementing an Objective-C-compatible library in Swift. 😕
