### ISSUE TITLE
OSRMTextInstructions issues

### ISSUE THREAD

**Issue by toothpiggystudio** [mapbox/MapboxDirections.swift#184]
Hi,

I got an issue on OSRMTextInstructions when i update my project to swift 4. Any fix on this one? 

Thanks.

![screen shot 2017-10-03 at 12 29 09 am](https://user-images.githubusercontent.com/28891494/31097965-26ad82c8-a7d2-11e7-95dd-f7927b9ca19e.png)

**Comment by 1ec5** [comment]
Hi, judging from your screenshot, you installed the Mapbox Navigation SDK using CocoaPods – is that correct? Xcode should be compiling OSRM Text Instructions as Swift 3, not Swift 4, so I’m a bit puzzled that this error is occurring.

**Comment by toothpiggystudio** [comment]
Hi, My previous project was on swift 3, then i converted it to swift 4 and i already fixed some of the errors but i stuck on this one.  Yup it was installed using CocoaPods, i also tried to removed and install it again but i got the same error.

**Comment by 1ec5** [comment]
Xcode 9 can handle mixing Swift 3 and Swift 4 dependencies in the same application. When converting your workspace to Swift 4, you should be able to opt out of converting OSRM Text Instructions to Swift 4.

**Comment by 1ec5** [comment]
#383 migrated to Swift 5.
