### ISSUE TITLE
RouteLeg Parsing Issue - Crashing all users 

### ISSUE THREAD

**Issue by DustinJia** [mapbox/MapboxDirections.swift#190]
<img width="876" alt="screen shot 2017-10-12 at 10 54 36 am" src="https://user-images.githubusercontent.com/8630438/31511215-da3734fe-af3b-11e7-9670-6b94e0781c24.png">

**Comment by frederoni** [comment]
Can you include the request URL?  Just strip out the token.

**Comment by DustinJia** [comment]
Here is the URL: https://api.mapbox.com/directions/v5/mapbox/walking/..., ..., 37.4157727.json?alternatives=false&geometries=polyline&overview=full&steps=true&continue_straight=false&roundabout_exits=true&annotations=duration,congestion&access_token= ...

From MBDirections.swift

**Comment by DustinJia** [comment]
@frederoni  Seems like this issue already been fixed somehow. Thanks!
