### ISSUE TITLE
Directions api returning routes treat each waypoint as destination

### ISSUE THREAD

**Issue by karthickkumarmr** [mapbox/MapboxDirections.swift#194]
If we request routes using Directions api with multiple waypoints (25 waypoints), the returned route assumes each waypoint as destination. 
Eg: While passing through the first waypoint, the voice instructions say, "In 500 feet You will arrive at your first destination".

Is there a way to treat the waypoints as just the points to pass through in the returned route and not treat them as destinations?

**Comment by karthickkumarmr** [comment]
@aag6z FYI

**Comment by karthickkumarmr** [comment]
Here is a screenshot highlighting the issue: You can see there are multiple "You have arrived at your destination" for every waypoint.
![multiplearrival](https://user-images.githubusercontent.com/5807998/31842833-e58f7ebe-b5a4-11e7-9aa5-38f50de438c3.jpg)

**Comment by PriyeshMohan** [comment]
@karthickkumarmr  any updates? Is there any way to remove the banners on the waypoints (1,2,3..etc) also? I would like to show the user the route with the origin and destination banners only!

**Comment by karthickkumarmr** [comment]
@PriyeshMohan I ended up customizing the library. This was more than a year ago. The latest library might be different and I have not tried it recently

**Comment by PriyeshMohan** [comment]
If we didn't specify the waypoints explicitly, every coordinate you passed is treated as a waypoint. So for eg - for a custom route, if we passed the coordinate array directly, the above notifications appear as soon as you reach each coordinate point.
You can do it using, 
```
//Points array
 let coordinates =   [
        CLLocationCoordinate2DMake(37.76556957793795, -122.42409811526268),
        CLLocationCoordinate2DMake(37.764725, -122.425349),
        CLLocationCoordinate2DMake(37.764665, -122.426482), .... ]
let routeOptions = NavigationMatchOptions(coordinates:coordinates)

//Specified the way point, source and destination
routeOptions.waypointIndices = IndexSet([0, coordinates1.count - 1])
Directions.shared.calculateRoutes(matching: routeOptions) { (waypoints, routes, error) in 
//Map match API response for custom route.
}
```

**Comment by treacher** [comment]
I’ve contacted support about this. There is a map matching api that is supposed to do what you need (it also allows a max of 100 way points). See the following blogpost: https://blog.mapbox.com/take-the-scenic-route-with-our-new-bring-your-own-route-feature-d3500a6a91c3 but I don’t think it’s supported in the iOS SDK but it seems to be in the Android SDK. They do have a rest API though for it. I’m going to dig around and see what I can get going tomorrow.

**Comment by PriyeshMohan** [comment]
@treacher , 
Yes, they support map matching for iOS also. See [https://docs.mapbox.com/ios/navigation/examples/custom-server/](url). In the `func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {` method, they requested a map matched route to travel. Each map match req can only have 100 points, but it can be increased according to the plan.
This link will also help, [https://docs.mapbox.com/ios/api/navigation/0.32.0/using-map-matching.html](url)

**Comment by 1ec5** [comment]
> Is there a way to treat the waypoints as just the points to pass through in the returned route and not treat them as destinations?
> Is there any way to remove the banners on the waypoints (1,2,3..etc) also?

#340 added the `Waypoint.separatesLegs` property that you can set to `false` on each waypoint you want to suppress.

> There is a map matching api that is supposed to do what you need (it also allows a max of 100 way points). See the following blogpost: https://blog.mapbox.com/take-the-scenic-route-with-our-new-bring-your-own-route-feature-d3500a6a91c3 but I don’t think it’s supported in the iOS SDK but it seems to be in the Android SDK.

Yes, this library does support the Map Matching API via the MatchOptions class and `Directions.calculate(_:completionHandler:)` method. However, it returns Match objects that are incompatible with the navigation SDK’s turn-by-turn navigation functionality.

Map matching is a rather specialized tool originally designed for cleaning up messy GPS traces after the fact. You can turn Map Matching API responses into Route objects using the `Directions.calculateRoutes(matching:completionHandler:)` method if the coordinates are coming from another routing engine - essentially, to “clean up” that routing engine’s output. On the other hand, if you just want to make sure the user passes through several important locations, try using the `Waypoint.separatesLegs` feature first, as it’s typically more robust for turn-by-turn navigation.
