### ISSUE TITLE
Update Polyline dependency for Swift 4 fix

### ISSUE THREAD

**Issue by wangela** [mapbox/MapboxDirections.swift#195]
Polyline v4.1.1 is breaking builds in Xcode 9 with iOS11.
https://github.com/raphaelmor/Polyline/tree/v4.2.0 has the fix to be compatible with Swift 4.

**Comment by 1ec5** [comment]
mapbox/MapboxDirections.swift#196 will upgrade to Swift 4. If you’re using Carthage, as in mapbox/mapbox-arkit-ios#23, then it’s supposed be possible to use MapboxDirections.swift and Polyline v4.1.1 as Swift 3 libraries even after you upgrade your application target to Swift 4. 🤔

**Comment by 1ec5** [comment]
v0.11.0 migrates to Swift 4.
