### ISSUE TITLE
Issue With PolyLine

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/MapboxDirections.swift#206]
Getting an error for PolyLine

[!] Unable to satisfy the following requirements:

- `Polyline (~> 4.2.0)` required by `Podfile`
- `Polyline (= 4.1.1)` required by `MapboxDirections.swift (0.12.0)`

**Comment by 1ec5** [comment]
v0.11.0 migrates to Swift 4 and Polyline v.4.2.
