### ISSUE TITLE
Please refactor your unwrapping optionals

### ISSUE THREAD

**Issue by AF-cgi** [mapbox/MapboxDirections.swift#228]
I use MapboxDirections 0.15.1. After response my crashed with an unwrapping optional issue in MBRouteStep line 600.
`let drivingSide = DrivingSide(description: json["driving_side"] as! String) ?? .right`
I resolve the issue by:
`let drivingSide = DrivingSide(description: json["driving_side"] as? String ?? "") ?? .right`
I can imaging that they are many other optional issues in the project.

**Comment by bsudekum** [comment]
Thanks for the bug report @AFcgi, this sounds reasonable to me.

**Comment by bsudekum** [comment]
Actually, after thinking about this more, `driving_side` is always present on a `RouteStep` when making a request to Mapbox Directions API. @AFcgi are you hitting our API or have you stood up your own server?

**Comment by AFcgi** [comment]
Hi @bsudekum,
thanks for your reply. We use an own server. The `driving_side` isn't present on our `RouteStep`. Also we use SwiftLint. One of these rules says do not unwrapped optionals in your code. So I think it's a better way to unwrap all your optionals.

**Comment by 1ec5** [comment]
Related: mapbox/MapboxGeocoder.swift#106.

We should replace most of the force-unwrapping and assertions with exceptions, reserving assertions for things that are entirely within the control of the client-side library (and not due to a malformed response or an error in the application code).

**Comment by 1ec5** [comment]
To clarify:

* When dealing with input from the developer or from the Directions API, throw exceptions.
* Otherwise, when dealing with data internal to the library, assert or force-unwrap (preferably the former).

In general, this means that initializers would be failable and non-initializers would have more assertions.

**Comment by 1ec5** [comment]
> In general, this means that initializers would be failable and non-initializers would have more assertions.

Migrating to JSONDecoder entails making the initializers failable. #221 still force-unwraps some things, but it should be much easier to throw instead now.

/cc @frederoni

**Comment by 1ec5** [comment]
#382 adopts Codable and eliminates nearly all assertions and upfront optional unwrapping.

**Comment by 1ec5** [comment]
#382 also added a preconditions to the coding methods that are enforced by force-unwrapping optionals. #388 makes the preconditions gentler by throwing errors instead, but that change should probably go in a separate PR.
