### ISSUE TITLE
Handling annotations click

### ISSUE THREAD

**Issue by Niduank** [mapbox/MapboxDirections.swift#229]
Hi,

I added polyline with MGLPolylineFeature as annotation (to customize polyline color).
Then I added a MGLPointAnnotation to add a marker.

This marker is over the polyline previously added.
When I select the MGLPointAnnotation, MGLNavigationMapView handle annotationSelected only for the polyline not for the marker.
I displayed [mapView selectedAnnotations] which only contains instance of MGLPolylineFeature.

How can I handle click on MGLPointAnnotation when this one is over another annotation ?

Thanks

**Comment by bsudekum** [comment]
Hey @Niduank, I think your question is intended for [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios). Would you mind re-opening your question there? Thanks!
