### ISSUE TITLE
How can get routes from multi waypoints(6) in map navigation swift?

### ISSUE THREAD

**Issue by AndreiOpanasenko** [mapbox/MapboxDirections.swift#231]
I am going to implement map navigation function using multi waypoints(6).

But, I can't know the solution now.

It works well for two points - user's current location and some point

but it don't works on multi waypoints.

Can you let me know the any solution?

Best regards

Andrei

**Comment by AFcgi** [comment]
I try it also. For me it works with 3 points, but the initializer has a assertion for > 25 waypoints. I don't understand it. I think it's possible up to 25 waypoints with the pay-as-you-go membership.

**Comment by captainbarbosa** [comment]
Hi @AndreiOpanasenko, MapboxDirections.swift uses the Mapbox Directions API to generate routes. If you're using the `automobileAvoidingTraffic` profile identifier, only three waypoints are allowed when calculating a route. Check out the [Mapbox Directions API documentation](https://www.mapbox.com/api-documentation/#directions) for more information.

All other [profile identifiers](https://www.mapbox.com/mapbox-navigation-ios/directions/0.18.0/Classes/RouteOptions.html#/c:@M@MapboxDirections@objc(cs)MBRouteOptions(py)profileIdentifier) allow you use up to 25 waypoints when calculating directions. I've opened https://github.com/mapbox/MapboxDirections.swift/issues/249 to help clarify the error one might run into when trying to use more then three waypoints when working with the `automobileAvoidingTraffic` profile identifier.
