### ISSUE TITLE
Assert because MGLAccountManager.setAccessToken is ignored by Directions class

### ISSUE THREAD

**Issue by cblu2016** [mapbox/MapboxDirections.swift#245]
This assert occurs when you specify the access token via MGLAccountManager.setAccessToken, but not in the plist:

"A Mapbox access token is required. Go to <https://www.mapbox.com/studio/account/tokens/>. In Info.plist, set the MGLMapboxAccessToken key to your access token, or use the Directions(accessToken:host:) initializer."

The code specified access token appears to be ignored here:

    /**
     The shared directions object.
     
     To use this object, a Mapbox [access token](https://www.mapbox.com/help/define-access-token/) should be specified in the `MGLMapboxAccessToken` key in the main application bundle’s Info.plist.
     */
    @objc(sharedDirections)
    open static let shared = Directions(accessToken: nil)

**Comment by 1ec5** [comment]
This library doesn’t depend on the map SDK, so it has no access to MGLAccountManager. As the assertion message states, you can either set the access token in your Info.plist or by creating a custom Directions object using `Directions(accessToken:host:)`. You can only use `Directions.shared` if you put the access token in your Info.plist.
