### ISSUE TITLE
Request and decode polyline encoding

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#26]
`geometry=polyline` results in _much_ smaller response sizes. We’d need to decode the polyline strings into the same array of coordinates we currently expose to client code.

/cc @bsudekum

**Comment by tmcw** [comment]
Can I write this? Even I could write this swift code :)

**Comment by tmcw** [comment]
Oh, actually: https://github.com/raphaelmor/Polyline

**Comment by 1ec5** [comment]
Yep. :smile:
