### ISSUE TITLE
Replace CocoaPods with Carthage for example application

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#28]
We currently rely on CocoaPods to manage dependencies for both building the framework locally and vending the framework to downstream CocoaPods users. We should replace the former usage with Carthage (or Swift Package Manager, perhaps) so that it’s easier to contribute to the project.

/cc @tmcw @boundsj

**Comment by boundsj** [comment]
@1ec5 @tmcw I've not used SPM myself but I found this talk useful:

https://realm.io/news/tryswift-jeff-hui-creating-a-swift-library

> The Swift Package Manager is actually a lot more work than the other two package managers and it’s still relatively new and ever evolving. In fact I updated it yesterday. It’s always changing. What’s interesting though is that Swift Package Manager is the only one that supports Linux. We’ll have to also support Linux in conjunction of supporting Swift Package Manager.

It sounds like Carthage may be the best choice for now but the future is interesting!

**Comment by Eldorado234** [comment]
#102 solves this issue (`swift3` only so far)

**Comment by 1ec5** [comment]
Fixed in #102 and #110.

**Comment by 1ec5** [comment]
> or Swift Package Manager, perhaps

Tracking SPM support in #234, though just for library distribution, not for the example applications.
