### ISSUE TITLE
MBRouteControllerProgressDidChangeNotification is not working

### ISSUE THREAD

**Issue by ptesting007** [mapbox/MapboxDirections.swift#287]
I have implemented mapbox map on my application and while I click on navigation for direction on that navigation map it is navigating to location but on my main map I am not able to check the progress of route.

I have use sample application from [https://github.com/mapbox/mapbox-navigation-ios](url)

I want Estimated time to reach at destination to track and update.

**Comment by frederoni** [comment]
The `MBRouteControllerProgressDidChangeNotification` notification belongs to [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios). Please open an issue there if you want to report a bug.
