### ISSUE TITLE
Switch to Alamofire for requests

### ISSUE THREAD

**Issue by tmcw** [mapbox/MapboxDirections.swift#29]
It's not possible to cleanly set a user agent header with RequestKit, and there are likely other methods that we'll need down the line, so let's switch to the battle-tested Alamofire.

**Comment by 1ec5** [comment]
This library was rewritten in #47 to remove RequestKit in favor of direction NSURLSession and NSHTTPURLResponse usage. There’s also a method that vends a URL you can use with any networking library you like, including Alamofire. These pieces will be unified when the three Mapbox Swift libraries are consolidated into one library. Are there any use cases left that would still require Alamofire?

**Comment by tmcw** [comment]
Sounds like Alamofire isn't necessary, which is great! Less complexity > more complexity.
