### ISSUE TITLE
Add Pause/Resume and progress updates to Directions.downloadTiles

### ISSUE THREAD

**Issue by frederoni** [mapbox/MapboxDirections.swift#306]
Tail work from https://github.com/mapbox/MapboxDirections.swift/pull/303

When the API provides support for `Content-Length` and range headers, we should add support for pause, resume, and reporting progress for `Directions.downloadTiles(in:version:session:completionHandler:)`

cc @1ec5 @JThramer

**Comment by 1ec5** [comment]
As of #353, `Directions.downloadTiles(in:version:completionHandler:)` will return a data task that the application can use to pause or cancel a download.

**Comment by 1ec5** [comment]
As of #353, the method returns a data task, so pausing and resuming is the responsibility of client code.
