### ISSUE TITLE
Offline Route

### ISSUE THREAD

**Issue by abozzelli** [mapbox/MapboxDirections.swift#315]
I need to store a Route to draw it on a MGLMapView offline. As I understand it's possible with the 0.25.0 release of MapboxDirection. Am I right? 
The most recent Pod of MapboxNavigation is using the 0.24.0 release, is the 0.25 around the corner?

**Comment by frederoni** [comment]
Storing a route and drawing on an MGLMapView offline is already possible.
You can either store the route’s `json` property and recreate it with `Route.init(json:waypoints:options:)` _or_ archive and unarchive the route with `NSKeyedArchiver` and `NSKeyedUnarchiver`.

However, with the new offline tile downloader, you can also calculate new routes entirely offline. The tiles that are downloaded with this library would have to be passed into `NavigationDirections`  provided by `MapboxCoreNavigation` in [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios). You are more than welcome to try out the `offline-routing` branch, but it is slated for 0.26.0.

To try it out, pin your dependency as follows:
```ruby
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :branch => "offline-routing"
```

**Comment by abozzelli** [comment]
many thanks!
