### ISSUE TITLE
Get distance to each waypoints on route

### ISSUE THREAD

**Issue by tezqa** [mapbox/MapboxDirections.swift#320]
Hello,

Is there a way to get distances from the start of the route or from the user location to each waypoint located on the route?

Thanks for you help!

**Comment by frederoni** [comment]
You can create CLLocation objects from the coordinates and use CoreLocation’s `CLLocation.distance(from:)` but that would measure the distance as the crow flies.

To calculate the distance along the route line, you would have to use something like [turf-swift](https://github.com/mapbox/turf-swift)’s `LineString.distance(from:to:)`.


```swift
import Turf

let lineString = LineString(route.coordinates)
let distance = lineString.distance(from: wp1.coordinate, to: wp2.coordinate)
```

**Comment by 1ec5** [comment]
The Directions API has added an explicit distance field to make this computation even easier: #333.
