### ISSUE TITLE
Origin of `bannerInstructions` and `voiceInstructions`

### ISSUE THREAD

**Issue by datwelk** [mapbox/MapboxDirections.swift#329]
I know that the `instruction` field of a `StepManeuver` object is coming directly from OSRMTI (OSRM Text Instructions). But how are the `bannerInstructions` and `voiceInstructions` fields on `RouteStep` generated from this data?

**Comment by 1ec5** [comment]
The Mapbox Directions API has an internal component that also uses OSRMTI to generate these fields. There’s some logic to concatenate distances and so forth, based on the `phrase`s in OSRMTI, as well as some miscellaneous logic for determining the distances at which to announce or display these instructions.
