### ISSUE TITLE
macOS, tvOS, watchOS not built on CI

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#337]
In #301, we nixed Bitrise builds for iOS, macOS, tvOS, and watchOS but only added a CircleCI build for iOS. We need to ensure that the CircleCI build covers all four platforms; otherwise, any problems will only be caught after release, when we push the pod to CocoaPods trunk and it fails verification.

/cc @mapbox/navigation-ios

**Comment by frederoni** [comment]
Looks like we did add all builds but they're part of the same job, just different steps:
![screenshot 2019-01-31 22 15 42](https://user-images.githubusercontent.com/764476/52085858-d54dfb80-25a5-11e9-9f26-f4f381ab807d.png)

Build and test on all platforms except for testing on watchOS for a reason I can't remember 🤔

**Comment by 1ec5** [comment]
Oh, I missed that somehow, OK. Sorry for the false alarm.

> Build and test on all platforms except for testing on watchOS for a reason I can't remember 🤔

XCTest is unavailable for watchOS, so that’s consistent with the old Bitrise app.
