### ISSUE TITLE
Add walking bias options

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#371]
The `mapbox/walking` profile now supports [three new parameters](https://docs.mapbox.com/api/navigation/#optional-parameters-for-the-mapboxwalking-profile), for now in the Directions API but soon in the Map Matching API as well:

* `walking_speed` – expose as `DirectionsOptions.speed`, of type `CLLocationSpeed` (measured in meters per second)
* `walkway_bias` – `DirectionsOptions.walkwayBias`, of type `Double` or `Float`
* `alley_bias` – `DirectionsOptions.alleyBias`, of type `Double` or `Float`

/cc @mapbox/navigation-ios @kevinkreiser

**Comment by 1ec5** [comment]
In the meantime, this should work for code written in Swift:

```swift
class SlowWalkRouteOptions: NavigationRouteOptions {
    override var urlQueryItems: [URLQueryItem] {
        return super.urlQueryItems + [
            URLQueryItem(name: "walking_speed", value: "0.14"),
            URLQueryItem(name: "alley_bias", value: "0.99"),
        ]
    }
}

let options = SlowWalkRouteOptions(coordinates: coordinates, profileIdentifier: .walking)
…
```

**Comment by JThramer** [comment]
It would be nice if these were exposed via a `UILayoutPriority`-like raw-value-backed enum. This way you could specify:

`NavigationBias.alwaysAvoid`

`NavigationBias.alwaysTake`

`NavigationBias.noPreference`

`NavigationBias(rawValue: 0.75)`

**Comment by frederoni** [comment]
This is happening in #370
