### ISSUE TITLE
Read access token from Info.plist

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#44]
As in mapbox/MapboxStatic.swift#19 and MapboxGeocoder.swift#40, the access token should be optional. When no access token is explicitly passed into MBDirections’ initializer, this library should get it from the `MGLMapboxAccessToken` key in the main bundle’s Info.plist, just like the Mapbox iOS SDK does.

/cc @friedbunny

**Comment by friedbunny** [comment]
👍
