### ISSUE TITLE
Serialize intersections field

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#59]
A `RouteStep` object in the response data now includes an `intersections` field that indicates the location and configuration of each intermediate intersection along the way between two maneuvers. The application can use this information to tighten up rerouting logic around known intersections. Currently the library drops this data, but it should be preserved in some object-oriented form.

/cc @willwhite @zugaldia

**Comment by zugaldia** [comment]
@1ec5 Thanks for the heads up, equivalent MAS ticket in https://github.com/mapbox/mapbox-java/issues/152.

**Comment by 1ec5** [comment]
Implemented in #80.
