### ISSUE TITLE
Swift 3 Migration

### ISSUE THREAD

**Issue by superpeteblaze** [mapbox/MapboxDirections.swift#61]
Hi guys,

I use MapboxDirections in my app (https://itunes.apple.com/ie/app/bikey/id1048962300?mt=8). 
I am migrating my app to Swift 3 in preparation for it's GA release and was wondering what the plans are with MapboxDirections.swift.

Do you guys have plans to get a Swift 3 branch up and running?

I would also love to contribute, so if you guys don't have plans to do this right now, I could definitely help out with this.

Best,
Pete

**Comment by 1ec5** [comment]
This is currently blocked by raphaelmor/Polyline#31, but a PR in the meantime for this library would be greatly appreciated.

**Comment by superpeteblaze** [comment]
Hey @1ec5, it looks like I don't have push access writes. I would like to push my WIP swift3 branch. Could you give me access please.

**Comment by 1ec5** [comment]
Added you as a collaborator, @superpeteblaze. Thanks!

**Comment by superpeteblaze** [comment]
Awesome @1ec5, thanks!

**Comment by superpeteblaze** [comment]
Hey @1ec5, I tried to push to repo but it looks like I still don't have access. As a test, I attempted to open the readme for editing on github to check my access and I get 'You’re editing a file in a project you don’t have write access to.'

Can you check my access settings again?

**Comment by 1ec5** [comment]
@superpeteblaze, GitHub says you have an [outstanding invitation](https://github.com/mapbox/MapboxDirections.swift/invitations). I think you’ll be able to push once you accept it.

**Comment by superpeteblaze** [comment]
Oh man, sorry about that @1ec5, must have missed a notification. Thanks man

**Comment by anatoliykant** [comment]
Hi guys,
What about Swift 3
When will release?

**Comment by superpeteblaze** [comment]
@anatoliykant There is already a Swift 3 branch. Just point your podfile to it as follows;
pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'

**Comment by anatoliykant** [comment]
Thanks a lot!!!

What's about mapbox ios sdk?
Have you plans to re-write them in swift3?

**Comment by 1ec5** [comment]
Be sure to follow #64 to find out when the Swift 3 branch gets merged to master.

> What's about mapbox ios sdk?
> Have you plans to re-write them in swift3?

The Mapbox iOS SDK’s public interface is written in Objective-C, which automatically bridges to whatever version of Swift you happen to be using.

For the time being, we have no plans to rewrite the SDK in Swift. The vast majority of the SDK is written in cross-platform C++, with a layer of Objective-C++ to bridge to the public Objective-C interface. Swift lacks support for C++ bridging. If C++ interoperability is added to Swift in the future, we’ll definitely take a rewrite into consideration.

In the meantime, if there are any pain points for working with the SDK in Swift, please raise them at the mapbox/mapbox-gl-native repository. It’s conceivable that we might provide a CocoaPods subspec with some Swift helpers the way [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs/) does.

**Comment by anatoliykant** [comment]
Thank you.

**Comment by 1ec5** [comment]
#64 landed, so the master branch is written in Swift 3, and so will the next release. Thanks to @superpeteblaze @Eldorado234 for helping with this migration, and to everyone for their patience.

If you specified `swift3` in your Podfile or Cartfile, please see the important note in https://github.com/mapbox/MapboxDirections.swift/pull/64#issuecomment-280970725.
