### ISSUE TITLE
Add cash toll only option to RoadClasses

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#618]
The Directions API now supports an `exclude=cash_only_tolls` parameter, regardless of routing profile. We should add a `cashTollOnly` option to the `RoadClasses` option set.

/cc @mapbox/navigation-ios @ktatterso @Guardiola31337

**Comment by jill-cardamon** [comment]
@1ec5 what was the reasoning between for this new RoadClass `cashTollOnly` as opposed to `cashOnlyToll`?
