### ISSUE TITLE
MBDirections  init return nil

### ISSUE THREAD

**Issue by iOSBoy** [mapbox/MapboxDirections.swift#87]
v0.6.0

NSString _token = @"pk.eyJ1IjoidG9ueWlvcyIsImEiOiJjaXU4MHo2dzYwMDFyMnlueHpkdTFtODZzIn0.o4m3pnlfCqUKGVCX-9_O_***";
MBDirections *directions = [[MBDirections alloc] initWithAccessToken:token];

who can help me  why the directions is return  nil

**Comment by 1ec5** [comment]
I’m unable to reproduce this issue. Can you try to reproduce it in v0.7.0?

**Comment by 1ec5** [comment]
I’m unaware of any way `directions` would wind up `nil` with this code. If you still reproduce the issue in v0.7.0 or above, please reopen this issue and we’ll take another look.
