### ISSUE TITLE
Crash when route does not contain lanes

### ISSUE THREAD

**Issue by bsudekum** [mapbox/MapboxDirections.swift#90]
![screen shot 2016-11-08 at 10 01 22 am](https://cloud.githubusercontent.com/assets/1058624/20110813/add01fa8-a59a-11e6-8c8c-c5c2740c02c7.png)

/cc @1ec5

**Comment by bsudekum** [comment]
Fixed, was not on latest.

**Comment by 1ec5** [comment]
Specifically, this was fixed by #89.
